remote_theme: "pages-themes/dinky"

plugins:
  - jekyll-remote-theme 
  - jekyll-include-cache 
  - jekyll-paginate

title: hola ASIR2

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

collections:
  members:
    output: true

# número de posts por página
paginate: 2
paginate_path: /blog/page:num/

name: oscar novillo

# Configuración específica para los posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
