remote_theme: pages-themes/slate@v0.2.0
title: Slate theme
description: Slate is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
#theme: minimal-mistakes-jekyll

plugins:
  - jekyll-remote-theme 
  - jekyll-include-cache # add this line to the plugins list if you already have one
  - jekyll-paginate

title: hola ASIR2

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
    # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

collections:
  members:
    output: true



# número de posts por página
paginate: 2
paginate_path: /blog/page:num/


name: Johnatan Jimenez Ortiz