site: JDox
title: JDox
greetings: Hi 👋
description: >-
  JDox is Jekyll blog theme powered by Github Pages
lang: en
image: https://res.cloudinary.com/notee/image/upload/v1640411291/notes/imgseo.jpg
timezone:  Asia/Jakarta
repo: https://github.com/aliifam/cnote # site repo [optional]
data-theme: light # default theme "dark" | "light"
discus-identifier: webthme
default-thumb: https://res.cloudinary.com/notee/image/upload/v1640412257/notes/default-thumb.webp

title: hola ASIR2

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
    # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

collections:
  members:
    output: true



# número de posts por página
paginate: 2
paginate_path: /blog/page:num/



minima:
  skin: dark

name: oscar novillo
  
