remote_theme: pages-themes/primer@v0.2.0
plugins:
  - jekyll-remote-theme 
  - jekyll-include-cache # add this line to the plugins list if you already have one
  - jekyll-paginate

title: Hola

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  
title: Jekyll Theme Primer
description: Primer is a Jekyll theme for GitHub Pages
    # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

collections:
  members:
    output: true



# número de posts por página
paginate: 2
paginate_path: /blog/page:num/





name: johnatan jimenez ortiz
  
